version: 2

jobs:
  build:
    working_directory: /var/www

    environment:
      BASH_ENV: ~/.bashrc

    docker:
      - image: php:7.1-cli
        environment:
          APP_ENV=testing

    steps:
      - run:
          name: Install system dependencies
          command: |
            apt update
            apt install -y git unzip sudo zlib1g-dev libmcrypt-dev libpng-dev libsqlite3-dev

      - run:
          name: Install php extensions
          command: docker-php-ext-install -j$(nproc) zip pdo_sqlite pdo_mysql gd mcrypt

      - checkout

      - run:
          name: Install NPM
          command: |
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            apt install -y nodejs

      - run:
          name: Install composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
            mv composer.phar /usr/local/bin/composer

      - run:
          name: Install composer dependencies
          command: composer install --no-progress --no-suggest

      - run:
          name: Configure environment
          command: |
            cp .env.example .env
            php artisan key:generate

      - run:
          name: Install node dependencies
          command: npm install

      - run:
          name: Build assets
          command: npm run dev

      - run:
          name: PHPUnit Tests
          command: ./vendor/bin/phpunit